spring.config.import=optional:file:.env.local[.properties]
spring.application.name=tradetier

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.mvc.pathmatch.matching-strategy=ant-path-matcher

application.security.jwt.secret-key=${JWT_SECRET}
application.security.jwt.expiration=${JWT_EXPIRATION_MS}
# application.security.jwt.refresh-token.expiration=${JWT_REFRESH_EXPIRATION_MS}
